### PR TITLE
Add GtkFileChooserNative

### PR DESCRIPTION
**Pull request by mwawra**
The Gtk file chooser dialogs looking pretty ugly on Win7, so I played around a little with the native file chooser dialogs from GtkFileChooserNative.

Beside the question if this is really useful for somebody else there are two remaining questions for me:
1. Since there is no destroy-function for GtkFileChooserNative do I have to use GLib.gc_unref(dlg) or something else?
2. Which functions have to be implemented in gen/gbox2 and gen/gbox3?

### CODE REVIEW

**Comment by tknopp** [comment]
is `GtkFileChooserNative` a regular widget? Its not clear to me where it is in the object hierarchy

**Comment by mwawra** [comment]
Very good question, sadly this was also unclear for me. I couldn't find this information in the Gtk documentation.

**Comment by tknopp** [comment]
I still can try to answer some questions:
 - the gen/ stuff is autogenerated. Using Clang.jl . You have to add your type here: https://github.com/JuliaGraphics/Gtk.jl/blob/master/gen/gtk_get_set_gen.jl

**Comment by mwawra** [comment]
Ok, thank you! I already added GtkFileChooserNative and GtkNativeDialog to gtk_get_set_gen.jl. Is there something else I have to do?

**Comment by tknopp** [comment]
you need to run this script. it will update gen/gbox2 and gen/gbox3

**Comment by tknopp** [comment]
And of course in order to be able of running the script you will need LLVM.jl (installed properly)

**Comment by mwawra** [comment]
Good to know, thank you! Since Gtk is currently not precompiling on Julia v0.7, I have to build Julia v0.6 to install LLVM properly. We will see how this works!

**Comment by tknopp** [comment]
Yes many packages on 0.7 are not working. We have to wait until the first betas.

**Comment by mwawra** [comment]
I hope the autogenerated files are ok. I had to tune gbox3 manually like in commit [d25c711](https://github.com/JuliaGraphics/Gtk.jl/commit/d25c711b5d0f60fc68789d545de9425d2fdad981) and gconsts3 seems to be much smaller then the former one.

**Comment by mwawra** [comment]
Maybe I don't installed all needed GTK-packages in Debian. Maybe LLVM.jl or Clang.jl are not installed properly. Since I couldn't use the option BUILD_LLVM_CLANG=1 with the v0.6.2 branch of Julia (not working anymore) I had to use the Clang-Packages that are bundled with Debian. And finding the right settings for installing Clang.jl under this conditions was not so easy.

**Comment by tknopp** [comment]
Ok, CI is passing, lets merge

**Comment by mwawra** [comment]
Thank you for the support! This was my first PR.

**Pull request merged**
