### PR TITLE
Use isdefined and Compat instead of unspecific VERSION conditions

### PR DESCRIPTION
**Pull request by tkelman**
take! requires minimum version of 0.9.5

ref https://github.com/JuliaGraphics/Gtk.jl/issues/263#issuecomment-281695222

### CODE REVIEW

**Comment by vtjnash** [comment]
Gtk is not compatible with Compat.String. It could use GLib.String if this really bothers you

**Comment by tkelman** [comment]
it's only used in the two places that call `take!` here

**Comment by timholy** [comment]
@tknopp, I turned on [attobot](https://github.com/attobot/attobot) so now you can make new releases using the GitHub GUI.

**Comment by timholy** [comment]
And I submitted a PR for v0.11.0

**Comment by tknopp** [comment]
@timholy thanks, attobot is really great!

**Pull request merged**
