### PR TITLE
add gl_area_set_required_version

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by tknopp** [comment]
nice, are you working on the Gtk integration of GLVisualize?

**Comment by SimonDanisch** [comment]
Yes! :) As a matter of fact, it's mostly integrated into [_Visualize_](https://github.com/SimonDanisch/Visualize.jl)!
I think I will rely on GTK more in the future -  at least to sketch out the interface for more complex UIs!

**Comment by tknopp** [comment]
@SimonDanisch: Good to here that we have partially convinced you that Gtk is a good toolkit ;-)

If you have some simple example of a volume rendering (or surface rendering) within a Gtk container I would be very interested in that.

**Comment by SimonDanisch** [comment]
I'm preparing one right now for my juliacon talk ;)

**Pull request merged**
