### PR TITLE
Add the game 2048 as an example.

### PR DESCRIPTION
**Pull request by wherrera10**
I think the package needs more examples, so here is one.

### CODE REVIEW

**Comment by tknopp** [comment]
good idea! But how does it work? I tried to press buttons but nothing changes.

**Comment by wherrera10** [comment]
Hm, portability. Arrow keys as in https://gabrielecirulli.github.io/2048/
should work. I may have to look at the relevant keyboards on OSX and so
forth.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tknopp** [comment]
yea this is on OS X

**Comment by tknopp** [comment]
Ok seems to work now. Could you add a link to the comments that gives a reference what this game is about? Will merge then.

**Comment by tknopp** [comment]
ok, ready to merge or do you plan tweaking more things?

**Comment by wherrera10** [comment]
Certainly should be able to merge.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Pull request merged**
