### PR TITLE
Fixed Overlay constructor 

### PR DESCRIPTION
**Pull request by sbrisson**
Added the missing title parameter in the Overlay constructor function in layouts.jl

### CODE REVIEW

**Comment by tknopp** [comment]
Hi thanks for making a pull request.

Have you tested this? By looking at the Gtk documentation:

https://developer.gnome.org/gtk3/stable/GtkOverlay.html#gtk-overlay-new

the `gtk_overlay_new` function seems to get no arguments at all.

**Comment by sbrisson** [comment]
No I'm a bit new to GitHub, how can I test using my modified repository? Also, I tried another fix and want to test it. @tknopp

**Comment by tknopp** [comment]
Thats absolute fine.
You have to make the changes in your Julia package directory:
`.julia/v0.5/Gtk/src`
Then you can modify the code until you have a version that works.

Nowadays it then might work to do `Pkg.publish()` in order to make a pull request, but I am not really sure. (will need help by package experts like @timholy)

When you test the new functionality you should directly add a test case to `test/gui.jl` at the end. So that we can be sure that it works. These test files are automatically be executed if you make a pull request.

**Comment by tknopp** [comment]
Here is a good description how to fix bugs in packages and automatically make a PR

http://docs.julialang.org/en/release-0.5/manual/packages/#executive-summary

**Comment by tknopp** [comment]
@sbrisson: Nice, thanks a bunch, this looks fine now. Do you plan to use Gtk.jl in a project or is this more playing around with the package?

**Comment by sbrisson** [comment]
@tknopp I'm using it for a project

**Comment by sbrisson** [comment]
@tknopp: also, on another note, I'm having trouble loading the Gtk documentation - are you having a similar issue?

**Comment by tknopp** [comment]
Which documentation, on the github website?

**Comment by sbrisson** [comment]
No, the developer website.

**Comment by tknopp** [comment]
a sorry, I though you meant the Gtk.jl documentation. I can't load Gtk3 documentation as well. Seems currently down

**Pull request merged**
