### PR TITLE
fix broken syntax on 0.5

### PR DESCRIPTION
**Pull request by KristofferC**
looks correct @stevengj?

ref https://github.com/JuliaLang/julia/pull/17393#issuecomment-234122725

### CODE REVIEW

**Comment by stevengj** [comment]
Yep.

**Comment by tknopp** [comment]
CI seems to be unhappy.

**Comment by stevengj** [comment]
Seems like an unrelated failure?

**Comment by KristofferC** [comment]
Only on Mac. Seems to be unrelated?

**Comment by lobingera** [comment]
> Only on Mac.

Some Mac users have strong oppinions on that...

I'm not an expert on this, but could it be another Homebrew hiccup?
```
> (<unknown>:50507): GdkPixbuf-WARNING **: Cannot open pixbuf loader module file '/Users/travis/.julia/v0.4/Homebrew/deps/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.

Try running the command

  gdk-pixbuf-query-loaders > /Users/travis/.julia/v0.4/Homebrew/deps/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache

to make things work again for the time being.
```

**Comment by tknopp** [comment]
@tkelman has activated CI on mac in #213.
What should we for this PR? Ignore CI on Mac?

**Comment by tkelman** [comment]
it worked a few weeks ago, ref https://travis-ci.org/JuliaGraphics/Gtk.jl/builds/142129851 - but Homebrew.jl has gone through some overhauls recently

**Comment by tknopp** [comment]
@tkelman: So, is it ok to ignore this for the current PR? The fix looks ok.

**Comment by KristofferC** [comment]
@lobingera my point was that if it only fails on mac then it is likely not the PR's fault since the change should be OS agnostic.

**Comment by lobingera** [comment]
@KristofferC I agree. But if building gtk3+ on travis creates a problem, another issue should be opened.

**Comment by KristofferC** [comment]
Please do.

**Pull request merged**
