### PR TITLE
Switch CI to GitHub Actions

### PR DESCRIPTION
**Pull request by giordano**
~This is still a work-in-progress~

### CODE REVIEW

**Comment by giordano** [comment]
@SaschaMann either I'm doing something wrong, or [the prefix doesn't seem to work](https://github.com/JuliaGraphics/Gtk.jl/pull/537/checks?check_run_id=1547437212#step:7:1):
```
Run julia-actions/julia-runtest@prefix
  with:
    inline: yes
    coverage: true
    depwarn: yes
    project: @.
```
For the record, xvfb and xauth are already installed in the workers environments

**Comment by giordano** [comment]
So much more green now than one hour ago!  In order for documentation deployment to actually work, someone needs to [setup the SSH deploy key](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh) for GitHub Actions

**Comment by tknopp** [comment]
I added the keys, please ping me once this is ready to go.

**Comment by giordano** [comment]
Good to go now!

Note that you may want to disable AppVeyor (in AppVeyor settings set the build to off) and remove its webhook in the repository settings

**Pull request merged**
