### PR TITLE
g_timeout_add and other things

### PR DESCRIPTION
**Pull request by jonathanBieler**
I've moved `g_timeout_add`, `g_idle_add`, and a couple of other things that I had in GtkExtensions.jl. I still have other things in there (text and tree related mainly) but I need to review them.

I've added tests for most of it, but no documentation.

### CODE REVIEW

**Comment by tknopp** [comment]
there are different test errors. The one on windows might be because the sleep needs to be longer?

**Comment by jonathanBieler** [comment]
There's probably an issue with this, I copied it from the signal_connect part but it might not be correct. I can reproduce the issue on Windows so I'll try to fix it.

https://github.com/JuliaGraphics/Gtk.jl/pull/395/files#diff-8c2b506e7179e52e816713686d731068R374

**Comment by jonathanBieler** [comment]
I'm not 100% sure about those `g_timeout_add`, but it seems to work for the most part.

**Comment by stevengj** [comment]
Now that Julia is getting full multi-threaded support in 1.3, you probably should add the thread-safe API function `gdk_threads_add_idle_full`.

**Comment by tknopp** [comment]
I think the `gdk` versions are deprecated, see
https://gitlab.gnome.org/GNOME/gtk/commit/334acbfc39cc08869932ec046e4d13e6c4b64be6

**Pull request merged**
