### PR TITLE
Put upper bounds on Cairo version

### PR DESCRIPTION
**Pull request by timholy**
This "future-proofs" for new releases of Gtk. Correcting the bounds on prior releases requires a PR directly to the General registry (so this does not suffice on its own).

I also took the opportunity to get rid of Compat.jl, is that OK?

### CODE REVIEW

**Comment by tknopp** [comment]
yes getting rid of Compact is fine.

**Comment by tknopp** [comment]
thanks!

**Comment by timholy** [comment]
Hmm, it's still using macOS 10.13 despite my efforts to change that. I suspect we should merge #438 if there are significant documentation improvements.

**Comment by tknopp** [comment]
yes lets do that. With BB on the horizon, we should give up on Mac for the transition time.

**Pull request merged**
