### PR TITLE
Fixed GtkFileFilter MethodError for ASCIIStrings in julia 0.4

### PR DESCRIPTION
**Pull request by Matt5sean3**
This pull request is meant to fix the problem described in #247 

In the current version
```julia
@GtkFileFilter("*.txt")
```
will fail with a `MethodError` in julia 0.4.6

This also means that 
```julia
open_dialog("Open a File", GtkNullContainer(), ("*.txt",  ))
```
fails in julia 0.4 while using that constructor.

Until this problem is fixed file filtering in dialogs is impossible in julia 0.4

### CODE REVIEW

**Comment by Matt5sean3** [comment]
After further examination, file filtering isn't strictly impossible, just a bit unwieldy and has some unexpected requirements:

This will succeed in creating an opener for csv files.
```julia
filter = @GtkFileFilter(; pattern=UTF8String("*.csv"), mimetype=UTF8String("text/csv"))
file_path = open_dialog("Open a File", GtkNullContainer(), (filter, ))
```

**Comment by tknopp** [comment]
@Matt5sean3: Seems correct to me. Could you please add a test for `@GtkFileFilter` so that we can check in the future that it works?

Thanks!

**Comment by Matt5sean3** [comment]
I've added tests for the current behavior seen in the `@GtkFileFilter` constructor. They seem to pass under Linux at least for v0.4 and v0.5.

**Comment by tknopp** [comment]
Thanks for the fix and adding the tests. I merged it for now, but why is the `GtkFileFilterInfo` just defined in the test file? Isn't this part of the API?

**Comment by Matt5sean3** [comment]
I added `GtkFileFilterInfo` just as part of the tests because the only places I saw it used was for `gtk_file_filter_filter`, and in the definition of `GtkFileFilterFunc` which is used by `gtk_file_filter_add_custom`, neither of which are wrapped anywhere in the current Julia Gtk package. This would have left that type without a use within the Gtk package itself. Adding wrappers for the functions that use `GtkFileFilterInfo` to the main package would have expanded the scope of the pull request beyond the stated goal so I kept it limited to the test files.

**Comment by Matt5sean3** [comment]
Also, there are some garbage collection pitfalls that could arise with the `GtkFileFilterInfo` type as currently defined, as the strings pointed to by the `filename`, `uri`, `display_name`, and `mime_type` members could be garbage collected if they aren't referenced elsewhere making the `GtkFileFilterInfo` as currently defined a bit too unsafe for general usage in my estimation.

**Comment by tknopp** [comment]
Yea thats seem reasonable then.

**Pull request merged**
