### PR TITLE
ComboBoxText: Add methods for setting/getting active index/text

### PR DESCRIPTION
**Pull request by BioTurboNick**
Provides for direct access to the index of the selected item and the selected text.

### CODE REVIEW

**Comment by tknopp** [comment]
isn't this captured by `GAccessor.active_text` and `Gtk.GAccessor.active`? Whenever we can we use the automatically generated accessors.

**Comment by BioTurboNick** [comment]
It could be, it's not well-documented though.

**Comment by BioTurboNick** [comment]
Ah, I think I see the intent. Nevermind then.

**Comment by tknopp** [comment]
yes, Gtk.jl could be much better documented. I did in the past exactly what you did until Jameson told me to use the GAccessor module.

**Comment by BioTurboNick** [comment]
Although, one issue is that `GAccessor.active_text()` can return a null pointer. Should this package be directly exposing that sort of thing, or Julia-izing it? (0-based to 1-based indexes, NULL => Nothing, etc.)

I see this has been raised before: https://github.com/JuliaGraphics/Gtk.jl/issues/274

**Comment by tknopp** [comment]
Absolutely, the current stage is not perfect. There is room for lots of improvements.

**Pull request closed without merging**
