### PR TITLE
Update async.md for 1.0 and Threading

### LINKED ISSUE #640: Async UI example needs updating
The example in this file needs updated:
https://github.com/JuliaGraphics/Gtk.jl/blob/master/docs/src/manual/async.md

I made a version that at least runs here: #636, but apparently there are even better ways to do it.

### PR DESCRIPTION
**Pull request by LilithHafner**
Closes #636
Closes #640

### CODE REVIEW

**Comment by tknopp** [comment]
I would actually remove the multi-process version.

**Comment by LilithHafner** [comment]
Really? When running the default `julia -t1` the Distributed approach works for me and the Threads approach stalls the UI.

**Comment by tknopp** [comment]
Because ist just works in toy examples for me. If the callback needs to call package code one needs to run Julia with -p and "@everywhere using ...". Data exchange ist also more complicated. For me the multi-threaded version is much simpler.

If I see it right, Julia 1.8 will give us the second thread by default.

**Comment by LilithHafner** [comment]
> If the callback needs to call package code one needs to run Julia with -p and "@Everywhere using ...". Data exchange ist also more complicated.

Noted. Threading certainly has advantages and should probably be listed first.

> If I see it right, Julia 1.8 will give us the second thread by default.

Where did you see that?

```julia
x@X ~ % julia +beta
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _' |  |
  | | |_| | | | (_| |  |  Version 1.8.0-rc3 (2022-07-13)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> Threads.nthreads()
1
```

In 1.9 we will have interactive threads which should make the threading approach more robust:

"Threads.@spawn now accepts an optional first argument: :default or :interactive. An interactive task desires low latency and implicitly agrees to be short duration or to yield frequently. Interactive tasks will run on interactive threads, if any are specified when Julia is started ([#42302])." (https://github.com/JuliaLang/julia/blob/df846436bb91b291be988f5e18e256d514b97347/NEWS.md)

I think the best option is probably to recommend threads and then afterward, note that Distributed is also an option with caveats.

**Comment by tknopp** [comment]
🙁 I thought this would be in 1.8.

But anyway. I like your suggestion of just switching the order.

**Comment by tknopp** [comment]
thanks!

**Pull request merged**
